//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Imageshift) DeepCopyInto(out *Imageshift) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Imageshift.
func (in *Imageshift) DeepCopy() *Imageshift {
	if in == nil {
		return nil
	}
	out := new(Imageshift)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Imageshift) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageshiftExactSwap) DeepCopyInto(out *ImageshiftExactSwap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageshiftExactSwap.
func (in *ImageshiftExactSwap) DeepCopy() *ImageshiftExactSwap {
	if in == nil {
		return nil
	}
	out := new(ImageshiftExactSwap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageshiftList) DeepCopyInto(out *ImageshiftList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Imageshift, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageshiftList.
func (in *ImageshiftList) DeepCopy() *ImageshiftList {
	if in == nil {
		return nil
	}
	out := new(ImageshiftList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImageshiftList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageshiftMapping) DeepCopyInto(out *ImageshiftMapping) {
	*out = *in
	if in.Swap != nil {
		in, out := &in.Swap, &out.Swap
		*out = make([]ImageshiftSwap, len(*in))
		copy(*out, *in)
	}
	if in.ExactSwap != nil {
		in, out := &in.ExactSwap, &out.ExactSwap
		*out = make([]ImageshiftExactSwap, len(*in))
		copy(*out, *in)
	}
	if in.RegexSwap != nil {
		in, out := &in.RegexSwap, &out.RegexSwap
		*out = make([]ImageshiftRegexSwap, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageshiftMapping.
func (in *ImageshiftMapping) DeepCopy() *ImageshiftMapping {
	if in == nil {
		return nil
	}
	out := new(ImageshiftMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageshiftRegexSwap) DeepCopyInto(out *ImageshiftRegexSwap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageshiftRegexSwap.
func (in *ImageshiftRegexSwap) DeepCopy() *ImageshiftRegexSwap {
	if in == nil {
		return nil
	}
	out := new(ImageshiftRegexSwap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageshiftSpec) DeepCopyInto(out *ImageshiftSpec) {
	*out = *in
	in.Mappings.DeepCopyInto(&out.Mappings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageshiftSpec.
func (in *ImageshiftSpec) DeepCopy() *ImageshiftSpec {
	if in == nil {
		return nil
	}
	out := new(ImageshiftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageshiftStatus) DeepCopyInto(out *ImageshiftStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastReconciled.DeepCopyInto(&out.LastReconciled)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageshiftStatus.
func (in *ImageshiftStatus) DeepCopy() *ImageshiftStatus {
	if in == nil {
		return nil
	}
	out := new(ImageshiftStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageshiftSwap) DeepCopyInto(out *ImageshiftSwap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageshiftSwap.
func (in *ImageshiftSwap) DeepCopy() *ImageshiftSwap {
	if in == nil {
		return nil
	}
	out := new(ImageshiftSwap)
	in.DeepCopyInto(out)
	return out
}
