apiVersion: imageshift.dev/v1
kind: Imageshift
metadata:
  labels:
    app.kubernetes.io/name: imageshift-v2
    app.kubernetes.io/managed-by: kustomize
  name: imageshift-sample
spec:
  mappings:
    exactSwap:
      - reference: asdasdbusybox
        target: busybox
